<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Eventuous.Testing" Version="0.16.4" />
        <PackageReference Include="TUnit" Version="1.53.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Slicent\Slicent.csproj" />
    </ItemGroup>

</Project>
